/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\public\models\Court.glb -o src/components/Court.jsx 
*/

import { useGLTF } from '@react-three/drei';
import { MeshStandardMaterial } from 'three';
import { RigidBody } from '@react-three/rapier';

export function Court(props) {
  const { nodes, materials } = useGLTF('/models/Court.glb');
  // Clone the original material and create a new MeshStandardMaterial

  const customMaterial = new MeshStandardMaterial({
    map: materials['Sprite Material'].map,
    normalMap: materials['Sprite Material'].normalMap,
    // metalness: 0.3,
    // roughness: 0.85,
    fog: false,
  });

  return (
    <group {...props} dispose={null} position={[0, -0.15, -4.8]}>
      <RigidBody type="fixed" name="floor" friction={20} colliders={'hull'}>
        <mesh
          geometry={nodes.Floor.geometry}
          material={customMaterial}
          position={[0, -0.8, 0]}
          scale={[15.9, 0.75, 6.994]}
          receiveShadow
        />
        <mesh
          geometry={nodes.Cube.geometry}
          material={customMaterial}
          position={[0, 3.144, 2.08]}
          scale={[0.555, 0.137, 1]}
        />
        <mesh
          geometry={nodes.Stands001.geometry}
          material={customMaterial}
          position={[0, 0.2, -3]}
          scale={[9, 0.25, 1]}
        />
        <mesh
          geometry={nodes.Stands004.geometry}
          material={customMaterial}
          position={[-12.015, 0.2, 5.437]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[5.67, 0.25, 1]}
        />
        <mesh
          geometry={nodes.Stands002.geometry}
          material={customMaterial}
          position={[12.042, 0.2, 5.387]}
          rotation={[0, -1.571, 0]}
          scale={[5.67, 0.25, 1]}
        />
        <mesh
          geometry={nodes.Step006.geometry}
          material={customMaterial}
          position={[0, 0.5, -1.95]}
          scale={[9, 0.05, 0.05]}
        />
        <mesh
          geometry={nodes.Step004.geometry}
          material={customMaterial}
          position={[0, 1, -2.95]}
          scale={[9, 0.05, 0.05]}
        />
        <mesh
          geometry={nodes.Step005.geometry}
          material={customMaterial}
          position={[0, 1.5, -3.95]}
          scale={[9, 0.05, 0.05]}
        />
        <mesh
          geometry={nodes.Step013.geometry}
          material={customMaterial}
          position={[-10.965, 0.5, 5.437]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[5.67, 0.05, 0.05]}
        />
        <mesh
          geometry={nodes.Step014.geometry}
          material={customMaterial}
          position={[-11.965, 1, 5.437]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[5.67, 0.05, 0.05]}
        />
        <mesh
          geometry={nodes.Step015.geometry}
          material={customMaterial}
          position={[-12.965, 1.5, 5.437]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[5.67, 0.05, 0.05]}
        />
        <mesh
          geometry={nodes.Step007.geometry}
          material={customMaterial}
          position={[10.992, 0.5, 5.387]}
          rotation={[0, -1.571, 0]}
          scale={[5.67, 0.05, 0.05]}
        />
        <mesh
          geometry={nodes.Step008.geometry}
          material={customMaterial}
          position={[11.992, 1, 5.387]}
          rotation={[0, -1.571, 0]}
          scale={[5.67, 0.05, 0.05]}
        />
        <mesh
          geometry={nodes.Step009.geometry}
          material={customMaterial}
          position={[12.992, 1.5, 5.387]}
          rotation={[0, -1.571, 0]}
          scale={[5.67, 0.05, 0.05]}
        />
        <mesh
          geometry={nodes.Stair001.geometry}
          material={customMaterial}
          position={[4, 0.175, -1.75]}
          scale={[1.25, 0.125, 0.25]}
        />
        <mesh
          geometry={nodes.Stair002.geometry}
          material={customMaterial}
          position={[3.972, 0.675, -2.75]}
          scale={[1.25, 0.125, 0.25]}
        />
        <mesh
          geometry={nodes.Stair003.geometry}
          material={customMaterial}
          position={[-4, 0.675, -2.75]}
          scale={[1.25, 0.125, 0.25]}
        />
        <mesh
          geometry={nodes.Stair004.geometry}
          material={customMaterial}
          position={[-3.987, 0.175, -1.75]}
          scale={[1.25, 0.125, 0.25]}
        />
        <mesh
          geometry={nodes.Stair005.geometry}
          material={customMaterial}
          position={[3.972, 1.175, -3.75]}
          scale={[1.25, 0.125, 0.25]}
        />
        <mesh
          geometry={nodes.Stair006.geometry}
          material={customMaterial}
          position={[-4, 1.175, -3.75]}
          scale={[1.25, 0.125, 0.25]}
        />
        <mesh
          geometry={nodes.Stair013.geometry}
          material={customMaterial}
          position={[-10.765, 0.175, 5.029]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.25, 0.125, 0.25]}
        />
        <mesh
          geometry={nodes.Stair014.geometry}
          material={customMaterial}
          position={[-11.765, 0.675, 5.057]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.25, 0.125, 0.25]}
        />
        <mesh
          geometry={nodes.Stair017.geometry}
          material={customMaterial}
          position={[-12.765, 1.175, 5.057]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.25, 0.125, 0.25]}
        />
        <mesh
          geometry={nodes.Stair010.geometry}
          material={customMaterial}
          position={[10.792, 0.175, 5.796]}
          rotation={[0, -1.571, 0]}
          scale={[1.25, 0.125, 0.25]}
        />
        <mesh
          geometry={nodes.Stair011.geometry}
          material={customMaterial}
          position={[11.792, 0.675, 5.767]}
          rotation={[0, -1.571, 0]}
          scale={[1.25, 0.125, 0.25]}
        />
        <mesh
          geometry={nodes.Stair012.geometry}
          material={customMaterial}
          position={[12.792, 1.175, 5.767]}
          rotation={[0, -1.571, 0]}
          scale={[1.25, 0.125, 0.25]}
        />
        <mesh geometry={nodes.Cube001.geometry} material={customMaterial} position={[-15.4, 0.45, -5.443]} />
        <mesh geometry={nodes.Cube002.geometry} material={customMaterial} position={[-15.4, 0.45, -2.443]} />
        <mesh geometry={nodes.Cube003.geometry} material={customMaterial} position={[-15.4, 0.45, 0.557]} />
        <mesh geometry={nodes.Cube004.geometry} material={customMaterial} position={[-15.4, 0.45, 3.557]} />
        <mesh geometry={nodes.Cube005.geometry} material={customMaterial} position={[-15.4, 0.45, 6.557]} />
        <mesh geometry={nodes.Cube006.geometry} material={customMaterial} position={[-15.4, 0.45, 9.557]} />
        <mesh geometry={nodes.Cube007.geometry} material={customMaterial} position={[-15.4, 0.45, 12.557]} />
        <mesh
          geometry={nodes.Cube008.geometry}
          material={customMaterial}
          position={[-13.4, 0.45, -6.443]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes.Cube009.geometry}
          material={customMaterial}
          position={[-10.4, 0.45, -6.443]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes.Cube010.geometry}
          material={customMaterial}
          position={[-7.4, 0.45, -6.443]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes.Cube011.geometry}
          material={customMaterial}
          position={[-4.4, 0.45, -6.443]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes.Cube012.geometry}
          material={customMaterial}
          position={[-1.4, 0.45, -6.443]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes.Cube013.geometry}
          material={customMaterial}
          position={[1.6, 0.45, -6.443]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes.Cube014.geometry}
          material={customMaterial}
          position={[4.6, 0.45, -6.443]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes.Cube015.geometry}
          material={customMaterial}
          position={[7.6, 0.45, -6.443]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes.Cube016.geometry}
          material={customMaterial}
          position={[10.6, 0.45, -6.443]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes.Cube017.geometry}
          material={customMaterial}
          position={[13.6, 0.45, -6.443]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh geometry={nodes.Cube018.geometry} material={customMaterial} position={[15.6, 0.45, -5.443]} />
        <mesh geometry={nodes.Cube019.geometry} material={customMaterial} position={[15.6, 0.45, -2.443]} />
        <mesh geometry={nodes.Cube020.geometry} material={customMaterial} position={[15.6, 0.45, 0.557]} />
        <mesh geometry={nodes.Cube021.geometry} material={customMaterial} position={[15.6, 0.45, 3.557]} />
        <mesh geometry={nodes.Cube022.geometry} material={customMaterial} position={[15.6, 0.45, 6.557]} />
        <mesh geometry={nodes.Cube024.geometry} material={customMaterial} position={[15.6, 0.45, 9.557]} />
        <mesh geometry={nodes.Cube025.geometry} material={customMaterial} position={[15.6, 0.45, 12.557]} />
        <mesh
          geometry={nodes.Cube023.geometry}
          material={customMaterial}
          position={[0, 0, -1]}
          scale={[11, 0.05, 1]}
          receiveShadow
        />
      </RigidBody>

      <RigidBody type="fixed" name="backboard" colliders="hull">
        <mesh geometry={nodes.Backboard.geometry} material={customMaterial} position={[0, 3.6, 1.73]} castShadow />
        <mesh geometry={nodes.Post.geometry} material={customMaterial} position={[0, 0.45, 0]} castShadow />
      </RigidBody>

      <RigidBody type="fixed" name="ring" colliders="trimesh">
        <mesh geometry={nodes.Torus.geometry} material={customMaterial} position={[0, 3.15, 2.4]} castShadow />
      </RigidBody>
    </group>
  );
}

useGLTF.preload('/models/Court.glb');
